/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersAccessRouteImport } from './routes/_app.users-access'
import { Route as AppTripsDeliveriesRouteImport } from './routes/_app.trips-deliveries'
import { Route as AppSystemSettingsRouteImport } from './routes/_app.system-settings'
import { Route as AppSafetyIncidentsRouteImport } from './routes/_app.safety-incidents'
import { Route as AppRouteIntelligenceRouteImport } from './routes/_app.route-intelligence'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppOrganisationRouteImport } from './routes/_app.organisation'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppKpiScorecardRouteImport } from './routes/_app.kpi-scorecard'
import { Route as AppFuelIntelligenceRouteImport } from './routes/_app.fuel-intelligence'
import { Route as AppFleetOperationsRouteImport } from './routes/_app.fleet-operations'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDispatchCenterRouteImport } from './routes/_app.dispatch-center'
import { Route as AppAuditTrailRouteImport } from './routes/_app.audit-trail'
import { Route as AppActionCenterRouteImport } from './routes/_app.action-center'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersAccessRoute = AppUsersAccessRouteImport.update({
  id: '/users-access',
  path: '/users-access',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsDeliveriesRoute = AppTripsDeliveriesRouteImport.update({
  id: '/trips-deliveries',
  path: '/trips-deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSettingsRoute = AppSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyIncidentsRoute = AppSafetyIncidentsRouteImport.update({
  id: '/safety-incidents',
  path: '/safety-incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppRouteIntelligenceRoute = AppRouteIntelligenceRouteImport.update({
  id: '/route-intelligence',
  path: '/route-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationRoute = AppOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiScorecardRoute = AppKpiScorecardRouteImport.update({
  id: '/kpi-scorecard',
  path: '/kpi-scorecard',
  getParentRoute: () => AppRoute,
} as any)
const AppFuelIntelligenceRoute = AppFuelIntelligenceRouteImport.update({
  id: '/fuel-intelligence',
  path: '/fuel-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetOperationsRoute = AppFleetOperationsRouteImport.update({
  id: '/fleet-operations',
  path: '/fleet-operations',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchCenterRoute = AppDispatchCenterRouteImport.update({
  id: '/dispatch-center',
  path: '/dispatch-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditTrailRoute = AppAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AppRoute,
} as any)
const AppActionCenterRoute = AppActionCenterRouteImport.update({
  id: '/action-center',
  path: '/action-center',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/action-center': typeof AppActionCenterRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/dispatch-center': typeof AppDispatchCenterRoute
  '/documents': typeof AppDocumentsRoute
  '/fleet-operations': typeof AppFleetOperationsRoute
  '/fuel-intelligence': typeof AppFuelIntelligenceRoute
  '/kpi-scorecard': typeof AppKpiScorecardRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/organisation': typeof AppOrganisationRoute
  '/reports': typeof AppReportsRoute
  '/route-intelligence': typeof AppRouteIntelligenceRoute
  '/safety-incidents': typeof AppSafetyIncidentsRoute
  '/system-settings': typeof AppSystemSettingsRoute
  '/trips-deliveries': typeof AppTripsDeliveriesRoute
  '/users-access': typeof AppUsersAccessRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/action-center': typeof AppActionCenterRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/dispatch-center': typeof AppDispatchCenterRoute
  '/documents': typeof AppDocumentsRoute
  '/fleet-operations': typeof AppFleetOperationsRoute
  '/fuel-intelligence': typeof AppFuelIntelligenceRoute
  '/kpi-scorecard': typeof AppKpiScorecardRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/organisation': typeof AppOrganisationRoute
  '/reports': typeof AppReportsRoute
  '/route-intelligence': typeof AppRouteIntelligenceRoute
  '/safety-incidents': typeof AppSafetyIncidentsRoute
  '/system-settings': typeof AppSystemSettingsRoute
  '/trips-deliveries': typeof AppTripsDeliveriesRoute
  '/users-access': typeof AppUsersAccessRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/_app/action-center': typeof AppActionCenterRoute
  '/_app/audit-trail': typeof AppAuditTrailRoute
  '/_app/dispatch-center': typeof AppDispatchCenterRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/fleet-operations': typeof AppFleetOperationsRoute
  '/_app/fuel-intelligence': typeof AppFuelIntelligenceRoute
  '/_app/kpi-scorecard': typeof AppKpiScorecardRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/organisation': typeof AppOrganisationRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/route-intelligence': typeof AppRouteIntelligenceRoute
  '/_app/safety-incidents': typeof AppSafetyIncidentsRoute
  '/_app/system-settings': typeof AppSystemSettingsRoute
  '/_app/trips-deliveries': typeof AppTripsDeliveriesRoute
  '/_app/users-access': typeof AppUsersAccessRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/register'
    | '/action-center'
    | '/audit-trail'
    | '/dispatch-center'
    | '/documents'
    | '/fleet-operations'
    | '/fuel-intelligence'
    | '/kpi-scorecard'
    | '/maintenance'
    | '/organisation'
    | '/reports'
    | '/route-intelligence'
    | '/safety-incidents'
    | '/system-settings'
    | '/trips-deliveries'
    | '/users-access'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/register'
    | '/action-center'
    | '/audit-trail'
    | '/dispatch-center'
    | '/documents'
    | '/fleet-operations'
    | '/fuel-intelligence'
    | '/kpi-scorecard'
    | '/maintenance'
    | '/organisation'
    | '/reports'
    | '/route-intelligence'
    | '/safety-incidents'
    | '/system-settings'
    | '/trips-deliveries'
    | '/users-access'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/register'
    | '/_app/action-center'
    | '/_app/audit-trail'
    | '/_app/dispatch-center'
    | '/_app/documents'
    | '/_app/fleet-operations'
    | '/_app/fuel-intelligence'
    | '/_app/kpi-scorecard'
    | '/_app/maintenance'
    | '/_app/organisation'
    | '/_app/reports'
    | '/_app/route-intelligence'
    | '/_app/safety-incidents'
    | '/_app/system-settings'
    | '/_app/trips-deliveries'
    | '/_app/users-access'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users-access': {
      id: '/_app/users-access'
      path: '/users-access'
      fullPath: '/users-access'
      preLoaderRoute: typeof AppUsersAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips-deliveries': {
      id: '/_app/trips-deliveries'
      path: '/trips-deliveries'
      fullPath: '/trips-deliveries'
      preLoaderRoute: typeof AppTripsDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-settings': {
      id: '/_app/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof AppSystemSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/safety-incidents': {
      id: '/_app/safety-incidents'
      path: '/safety-incidents'
      fullPath: '/safety-incidents'
      preLoaderRoute: typeof AppSafetyIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/route-intelligence': {
      id: '/_app/route-intelligence'
      path: '/route-intelligence'
      fullPath: '/route-intelligence'
      preLoaderRoute: typeof AppRouteIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisation': {
      id: '/_app/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof AppOrganisationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpi-scorecard': {
      id: '/_app/kpi-scorecard'
      path: '/kpi-scorecard'
      fullPath: '/kpi-scorecard'
      preLoaderRoute: typeof AppKpiScorecardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fuel-intelligence': {
      id: '/_app/fuel-intelligence'
      path: '/fuel-intelligence'
      fullPath: '/fuel-intelligence'
      preLoaderRoute: typeof AppFuelIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet-operations': {
      id: '/_app/fleet-operations'
      path: '/fleet-operations'
      fullPath: '/fleet-operations'
      preLoaderRoute: typeof AppFleetOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch-center': {
      id: '/_app/dispatch-center'
      path: '/dispatch-center'
      fullPath: '/dispatch-center'
      preLoaderRoute: typeof AppDispatchCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-trail': {
      id: '/_app/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AppAuditTrailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action-center': {
      id: '/_app/action-center'
      path: '/action-center'
      fullPath: '/action-center'
      preLoaderRoute: typeof AppActionCenterRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionCenterRoute: typeof AppActionCenterRoute
  AppAuditTrailRoute: typeof AppAuditTrailRoute
  AppDispatchCenterRoute: typeof AppDispatchCenterRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFleetOperationsRoute: typeof AppFleetOperationsRoute
  AppFuelIntelligenceRoute: typeof AppFuelIntelligenceRoute
  AppKpiScorecardRoute: typeof AppKpiScorecardRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppOrganisationRoute: typeof AppOrganisationRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRouteIntelligenceRoute: typeof AppRouteIntelligenceRoute
  AppSafetyIncidentsRoute: typeof AppSafetyIncidentsRoute
  AppSystemSettingsRoute: typeof AppSystemSettingsRoute
  AppTripsDeliveriesRoute: typeof AppTripsDeliveriesRoute
  AppUsersAccessRoute: typeof AppUsersAccessRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionCenterRoute: AppActionCenterRoute,
  AppAuditTrailRoute: AppAuditTrailRoute,
  AppDispatchCenterRoute: AppDispatchCenterRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFleetOperationsRoute: AppFleetOperationsRoute,
  AppFuelIntelligenceRoute: AppFuelIntelligenceRoute,
  AppKpiScorecardRoute: AppKpiScorecardRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppOrganisationRoute: AppOrganisationRoute,
  AppReportsRoute: AppReportsRoute,
  AppRouteIntelligenceRoute: AppRouteIntelligenceRoute,
  AppSafetyIncidentsRoute: AppSafetyIncidentsRoute,
  AppSystemSettingsRoute: AppSystemSettingsRoute,
  AppTripsDeliveriesRoute: AppTripsDeliveriesRoute,
  AppUsersAccessRoute: AppUsersAccessRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
