/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganisationOrgSlugRouteImport } from './routes/organisation.$orgSlug'
import { Route as OrganisationOrgSlugLoginRouteImport } from './routes/organisation.$orgSlug.login'
import { Route as OrganisationOrgSlugWorkspaceRouteImport } from './routes/organisation.$orgSlug._workspace'
import { Route as OrganisationOrgSlugWorkspaceIndexRouteImport } from './routes/organisation.$orgSlug._workspace.index'
import { Route as OrganisationOrgSlugWorkspaceUsersAccessRouteImport } from './routes/organisation.$orgSlug._workspace.users-access'
import { Route as OrganisationOrgSlugWorkspaceTripsDeliveriesRouteImport } from './routes/organisation.$orgSlug._workspace.trips-deliveries'
import { Route as OrganisationOrgSlugWorkspaceSystemSettingsRouteImport } from './routes/organisation.$orgSlug._workspace.system-settings'
import { Route as OrganisationOrgSlugWorkspaceSafetyIncidentsRouteImport } from './routes/organisation.$orgSlug._workspace.safety-incidents'
import { Route as OrganisationOrgSlugWorkspaceRouteIntelligenceRouteImport } from './routes/organisation.$orgSlug._workspace.route-intelligence'
import { Route as OrganisationOrgSlugWorkspaceReportsRouteImport } from './routes/organisation.$orgSlug._workspace.reports'
import { Route as OrganisationOrgSlugWorkspaceOrganisationRouteImport } from './routes/organisation.$orgSlug._workspace.organisation'
import { Route as OrganisationOrgSlugWorkspaceMaintenanceRouteImport } from './routes/organisation.$orgSlug._workspace.maintenance'
import { Route as OrganisationOrgSlugWorkspaceKpiScorecardRouteImport } from './routes/organisation.$orgSlug._workspace.kpi-scorecard'
import { Route as OrganisationOrgSlugWorkspaceFuelIntelligenceRouteImport } from './routes/organisation.$orgSlug._workspace.fuel-intelligence'
import { Route as OrganisationOrgSlugWorkspaceFleetOperationsRouteImport } from './routes/organisation.$orgSlug._workspace.fleet-operations'
import { Route as OrganisationOrgSlugWorkspaceDocumentsRouteImport } from './routes/organisation.$orgSlug._workspace.documents'
import { Route as OrganisationOrgSlugWorkspaceDispatchCenterRouteImport } from './routes/organisation.$orgSlug._workspace.dispatch-center'
import { Route as OrganisationOrgSlugWorkspaceAuditTrailRouteImport } from './routes/organisation.$orgSlug._workspace.audit-trail'
import { Route as OrganisationOrgSlugWorkspaceActionCenterRouteImport } from './routes/organisation.$orgSlug._workspace.action-center'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationOrgSlugRoute = OrganisationOrgSlugRouteImport.update({
  id: '/organisation/$orgSlug',
  path: '/organisation/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationOrgSlugLoginRoute =
  OrganisationOrgSlugLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => OrganisationOrgSlugRoute,
  } as any)
const OrganisationOrgSlugWorkspaceRoute =
  OrganisationOrgSlugWorkspaceRouteImport.update({
    id: '/_workspace',
    getParentRoute: () => OrganisationOrgSlugRoute,
  } as any)
const OrganisationOrgSlugWorkspaceIndexRoute =
  OrganisationOrgSlugWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceUsersAccessRoute =
  OrganisationOrgSlugWorkspaceUsersAccessRouteImport.update({
    id: '/users-access',
    path: '/users-access',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceTripsDeliveriesRoute =
  OrganisationOrgSlugWorkspaceTripsDeliveriesRouteImport.update({
    id: '/trips-deliveries',
    path: '/trips-deliveries',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceSystemSettingsRoute =
  OrganisationOrgSlugWorkspaceSystemSettingsRouteImport.update({
    id: '/system-settings',
    path: '/system-settings',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceSafetyIncidentsRoute =
  OrganisationOrgSlugWorkspaceSafetyIncidentsRouteImport.update({
    id: '/safety-incidents',
    path: '/safety-incidents',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceRouteIntelligenceRoute =
  OrganisationOrgSlugWorkspaceRouteIntelligenceRouteImport.update({
    id: '/route-intelligence',
    path: '/route-intelligence',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceReportsRoute =
  OrganisationOrgSlugWorkspaceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceOrganisationRoute =
  OrganisationOrgSlugWorkspaceOrganisationRouteImport.update({
    id: '/organisation',
    path: '/organisation',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceMaintenanceRoute =
  OrganisationOrgSlugWorkspaceMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceKpiScorecardRoute =
  OrganisationOrgSlugWorkspaceKpiScorecardRouteImport.update({
    id: '/kpi-scorecard',
    path: '/kpi-scorecard',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceFuelIntelligenceRoute =
  OrganisationOrgSlugWorkspaceFuelIntelligenceRouteImport.update({
    id: '/fuel-intelligence',
    path: '/fuel-intelligence',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceFleetOperationsRoute =
  OrganisationOrgSlugWorkspaceFleetOperationsRouteImport.update({
    id: '/fleet-operations',
    path: '/fleet-operations',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceDocumentsRoute =
  OrganisationOrgSlugWorkspaceDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceDispatchCenterRoute =
  OrganisationOrgSlugWorkspaceDispatchCenterRouteImport.update({
    id: '/dispatch-center',
    path: '/dispatch-center',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceAuditTrailRoute =
  OrganisationOrgSlugWorkspaceAuditTrailRouteImport.update({
    id: '/audit-trail',
    path: '/audit-trail',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)
const OrganisationOrgSlugWorkspaceActionCenterRoute =
  OrganisationOrgSlugWorkspaceActionCenterRouteImport.update({
    id: '/action-center',
    path: '/action-center',
    getParentRoute: () => OrganisationOrgSlugWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organisation/$orgSlug': typeof OrganisationOrgSlugRouteWithChildren
  '/organisation/$orgSlug/login': typeof OrganisationOrgSlugLoginRoute
  '/organisation/$orgSlug/action-center': typeof OrganisationOrgSlugWorkspaceActionCenterRoute
  '/organisation/$orgSlug/audit-trail': typeof OrganisationOrgSlugWorkspaceAuditTrailRoute
  '/organisation/$orgSlug/dispatch-center': typeof OrganisationOrgSlugWorkspaceDispatchCenterRoute
  '/organisation/$orgSlug/documents': typeof OrganisationOrgSlugWorkspaceDocumentsRoute
  '/organisation/$orgSlug/fleet-operations': typeof OrganisationOrgSlugWorkspaceFleetOperationsRoute
  '/organisation/$orgSlug/fuel-intelligence': typeof OrganisationOrgSlugWorkspaceFuelIntelligenceRoute
  '/organisation/$orgSlug/kpi-scorecard': typeof OrganisationOrgSlugWorkspaceKpiScorecardRoute
  '/organisation/$orgSlug/maintenance': typeof OrganisationOrgSlugWorkspaceMaintenanceRoute
  '/organisation/$orgSlug/organisation': typeof OrganisationOrgSlugWorkspaceOrganisationRoute
  '/organisation/$orgSlug/reports': typeof OrganisationOrgSlugWorkspaceReportsRoute
  '/organisation/$orgSlug/route-intelligence': typeof OrganisationOrgSlugWorkspaceRouteIntelligenceRoute
  '/organisation/$orgSlug/safety-incidents': typeof OrganisationOrgSlugWorkspaceSafetyIncidentsRoute
  '/organisation/$orgSlug/system-settings': typeof OrganisationOrgSlugWorkspaceSystemSettingsRoute
  '/organisation/$orgSlug/trips-deliveries': typeof OrganisationOrgSlugWorkspaceTripsDeliveriesRoute
  '/organisation/$orgSlug/users-access': typeof OrganisationOrgSlugWorkspaceUsersAccessRoute
  '/organisation/$orgSlug/': typeof OrganisationOrgSlugWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organisation/$orgSlug': typeof OrganisationOrgSlugWorkspaceIndexRoute
  '/organisation/$orgSlug/login': typeof OrganisationOrgSlugLoginRoute
  '/organisation/$orgSlug/action-center': typeof OrganisationOrgSlugWorkspaceActionCenterRoute
  '/organisation/$orgSlug/audit-trail': typeof OrganisationOrgSlugWorkspaceAuditTrailRoute
  '/organisation/$orgSlug/dispatch-center': typeof OrganisationOrgSlugWorkspaceDispatchCenterRoute
  '/organisation/$orgSlug/documents': typeof OrganisationOrgSlugWorkspaceDocumentsRoute
  '/organisation/$orgSlug/fleet-operations': typeof OrganisationOrgSlugWorkspaceFleetOperationsRoute
  '/organisation/$orgSlug/fuel-intelligence': typeof OrganisationOrgSlugWorkspaceFuelIntelligenceRoute
  '/organisation/$orgSlug/kpi-scorecard': typeof OrganisationOrgSlugWorkspaceKpiScorecardRoute
  '/organisation/$orgSlug/maintenance': typeof OrganisationOrgSlugWorkspaceMaintenanceRoute
  '/organisation/$orgSlug/organisation': typeof OrganisationOrgSlugWorkspaceOrganisationRoute
  '/organisation/$orgSlug/reports': typeof OrganisationOrgSlugWorkspaceReportsRoute
  '/organisation/$orgSlug/route-intelligence': typeof OrganisationOrgSlugWorkspaceRouteIntelligenceRoute
  '/organisation/$orgSlug/safety-incidents': typeof OrganisationOrgSlugWorkspaceSafetyIncidentsRoute
  '/organisation/$orgSlug/system-settings': typeof OrganisationOrgSlugWorkspaceSystemSettingsRoute
  '/organisation/$orgSlug/trips-deliveries': typeof OrganisationOrgSlugWorkspaceTripsDeliveriesRoute
  '/organisation/$orgSlug/users-access': typeof OrganisationOrgSlugWorkspaceUsersAccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organisation/$orgSlug': typeof OrganisationOrgSlugRouteWithChildren
  '/organisation/$orgSlug/_workspace': typeof OrganisationOrgSlugWorkspaceRouteWithChildren
  '/organisation/$orgSlug/login': typeof OrganisationOrgSlugLoginRoute
  '/organisation/$orgSlug/_workspace/action-center': typeof OrganisationOrgSlugWorkspaceActionCenterRoute
  '/organisation/$orgSlug/_workspace/audit-trail': typeof OrganisationOrgSlugWorkspaceAuditTrailRoute
  '/organisation/$orgSlug/_workspace/dispatch-center': typeof OrganisationOrgSlugWorkspaceDispatchCenterRoute
  '/organisation/$orgSlug/_workspace/documents': typeof OrganisationOrgSlugWorkspaceDocumentsRoute
  '/organisation/$orgSlug/_workspace/fleet-operations': typeof OrganisationOrgSlugWorkspaceFleetOperationsRoute
  '/organisation/$orgSlug/_workspace/fuel-intelligence': typeof OrganisationOrgSlugWorkspaceFuelIntelligenceRoute
  '/organisation/$orgSlug/_workspace/kpi-scorecard': typeof OrganisationOrgSlugWorkspaceKpiScorecardRoute
  '/organisation/$orgSlug/_workspace/maintenance': typeof OrganisationOrgSlugWorkspaceMaintenanceRoute
  '/organisation/$orgSlug/_workspace/organisation': typeof OrganisationOrgSlugWorkspaceOrganisationRoute
  '/organisation/$orgSlug/_workspace/reports': typeof OrganisationOrgSlugWorkspaceReportsRoute
  '/organisation/$orgSlug/_workspace/route-intelligence': typeof OrganisationOrgSlugWorkspaceRouteIntelligenceRoute
  '/organisation/$orgSlug/_workspace/safety-incidents': typeof OrganisationOrgSlugWorkspaceSafetyIncidentsRoute
  '/organisation/$orgSlug/_workspace/system-settings': typeof OrganisationOrgSlugWorkspaceSystemSettingsRoute
  '/organisation/$orgSlug/_workspace/trips-deliveries': typeof OrganisationOrgSlugWorkspaceTripsDeliveriesRoute
  '/organisation/$orgSlug/_workspace/users-access': typeof OrganisationOrgSlugWorkspaceUsersAccessRoute
  '/organisation/$orgSlug/_workspace/': typeof OrganisationOrgSlugWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/organisation/$orgSlug'
    | '/organisation/$orgSlug/login'
    | '/organisation/$orgSlug/action-center'
    | '/organisation/$orgSlug/audit-trail'
    | '/organisation/$orgSlug/dispatch-center'
    | '/organisation/$orgSlug/documents'
    | '/organisation/$orgSlug/fleet-operations'
    | '/organisation/$orgSlug/fuel-intelligence'
    | '/organisation/$orgSlug/kpi-scorecard'
    | '/organisation/$orgSlug/maintenance'
    | '/organisation/$orgSlug/organisation'
    | '/organisation/$orgSlug/reports'
    | '/organisation/$orgSlug/route-intelligence'
    | '/organisation/$orgSlug/safety-incidents'
    | '/organisation/$orgSlug/system-settings'
    | '/organisation/$orgSlug/trips-deliveries'
    | '/organisation/$orgSlug/users-access'
    | '/organisation/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/organisation/$orgSlug'
    | '/organisation/$orgSlug/login'
    | '/organisation/$orgSlug/action-center'
    | '/organisation/$orgSlug/audit-trail'
    | '/organisation/$orgSlug/dispatch-center'
    | '/organisation/$orgSlug/documents'
    | '/organisation/$orgSlug/fleet-operations'
    | '/organisation/$orgSlug/fuel-intelligence'
    | '/organisation/$orgSlug/kpi-scorecard'
    | '/organisation/$orgSlug/maintenance'
    | '/organisation/$orgSlug/organisation'
    | '/organisation/$orgSlug/reports'
    | '/organisation/$orgSlug/route-intelligence'
    | '/organisation/$orgSlug/safety-incidents'
    | '/organisation/$orgSlug/system-settings'
    | '/organisation/$orgSlug/trips-deliveries'
    | '/organisation/$orgSlug/users-access'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/organisation/$orgSlug'
    | '/organisation/$orgSlug/_workspace'
    | '/organisation/$orgSlug/login'
    | '/organisation/$orgSlug/_workspace/action-center'
    | '/organisation/$orgSlug/_workspace/audit-trail'
    | '/organisation/$orgSlug/_workspace/dispatch-center'
    | '/organisation/$orgSlug/_workspace/documents'
    | '/organisation/$orgSlug/_workspace/fleet-operations'
    | '/organisation/$orgSlug/_workspace/fuel-intelligence'
    | '/organisation/$orgSlug/_workspace/kpi-scorecard'
    | '/organisation/$orgSlug/_workspace/maintenance'
    | '/organisation/$orgSlug/_workspace/organisation'
    | '/organisation/$orgSlug/_workspace/reports'
    | '/organisation/$orgSlug/_workspace/route-intelligence'
    | '/organisation/$orgSlug/_workspace/safety-incidents'
    | '/organisation/$orgSlug/_workspace/system-settings'
    | '/organisation/$orgSlug/_workspace/trips-deliveries'
    | '/organisation/$orgSlug/_workspace/users-access'
    | '/organisation/$orgSlug/_workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OrganisationOrgSlugRoute: typeof OrganisationOrgSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation/$orgSlug': {
      id: '/organisation/$orgSlug'
      path: '/organisation/$orgSlug'
      fullPath: '/organisation/$orgSlug'
      preLoaderRoute: typeof OrganisationOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation/$orgSlug/login': {
      id: '/organisation/$orgSlug/login'
      path: '/login'
      fullPath: '/organisation/$orgSlug/login'
      preLoaderRoute: typeof OrganisationOrgSlugLoginRouteImport
      parentRoute: typeof OrganisationOrgSlugRoute
    }
    '/organisation/$orgSlug/_workspace': {
      id: '/organisation/$orgSlug/_workspace'
      path: ''
      fullPath: '/organisation/$orgSlug'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceRouteImport
      parentRoute: typeof OrganisationOrgSlugRoute
    }
    '/organisation/$orgSlug/_workspace/': {
      id: '/organisation/$orgSlug/_workspace/'
      path: '/'
      fullPath: '/organisation/$orgSlug/'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceIndexRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/users-access': {
      id: '/organisation/$orgSlug/_workspace/users-access'
      path: '/users-access'
      fullPath: '/organisation/$orgSlug/users-access'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceUsersAccessRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/trips-deliveries': {
      id: '/organisation/$orgSlug/_workspace/trips-deliveries'
      path: '/trips-deliveries'
      fullPath: '/organisation/$orgSlug/trips-deliveries'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceTripsDeliveriesRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/system-settings': {
      id: '/organisation/$orgSlug/_workspace/system-settings'
      path: '/system-settings'
      fullPath: '/organisation/$orgSlug/system-settings'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceSystemSettingsRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/safety-incidents': {
      id: '/organisation/$orgSlug/_workspace/safety-incidents'
      path: '/safety-incidents'
      fullPath: '/organisation/$orgSlug/safety-incidents'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceSafetyIncidentsRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/route-intelligence': {
      id: '/organisation/$orgSlug/_workspace/route-intelligence'
      path: '/route-intelligence'
      fullPath: '/organisation/$orgSlug/route-intelligence'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceRouteIntelligenceRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/reports': {
      id: '/organisation/$orgSlug/_workspace/reports'
      path: '/reports'
      fullPath: '/organisation/$orgSlug/reports'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceReportsRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/organisation': {
      id: '/organisation/$orgSlug/_workspace/organisation'
      path: '/organisation'
      fullPath: '/organisation/$orgSlug/organisation'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceOrganisationRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/maintenance': {
      id: '/organisation/$orgSlug/_workspace/maintenance'
      path: '/maintenance'
      fullPath: '/organisation/$orgSlug/maintenance'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceMaintenanceRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/kpi-scorecard': {
      id: '/organisation/$orgSlug/_workspace/kpi-scorecard'
      path: '/kpi-scorecard'
      fullPath: '/organisation/$orgSlug/kpi-scorecard'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceKpiScorecardRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/fuel-intelligence': {
      id: '/organisation/$orgSlug/_workspace/fuel-intelligence'
      path: '/fuel-intelligence'
      fullPath: '/organisation/$orgSlug/fuel-intelligence'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceFuelIntelligenceRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/fleet-operations': {
      id: '/organisation/$orgSlug/_workspace/fleet-operations'
      path: '/fleet-operations'
      fullPath: '/organisation/$orgSlug/fleet-operations'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceFleetOperationsRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/documents': {
      id: '/organisation/$orgSlug/_workspace/documents'
      path: '/documents'
      fullPath: '/organisation/$orgSlug/documents'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceDocumentsRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/dispatch-center': {
      id: '/organisation/$orgSlug/_workspace/dispatch-center'
      path: '/dispatch-center'
      fullPath: '/organisation/$orgSlug/dispatch-center'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceDispatchCenterRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/audit-trail': {
      id: '/organisation/$orgSlug/_workspace/audit-trail'
      path: '/audit-trail'
      fullPath: '/organisation/$orgSlug/audit-trail'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceAuditTrailRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
    '/organisation/$orgSlug/_workspace/action-center': {
      id: '/organisation/$orgSlug/_workspace/action-center'
      path: '/action-center'
      fullPath: '/organisation/$orgSlug/action-center'
      preLoaderRoute: typeof OrganisationOrgSlugWorkspaceActionCenterRouteImport
      parentRoute: typeof OrganisationOrgSlugWorkspaceRoute
    }
  }
}

interface OrganisationOrgSlugWorkspaceRouteChildren {
  OrganisationOrgSlugWorkspaceActionCenterRoute: typeof OrganisationOrgSlugWorkspaceActionCenterRoute
  OrganisationOrgSlugWorkspaceAuditTrailRoute: typeof OrganisationOrgSlugWorkspaceAuditTrailRoute
  OrganisationOrgSlugWorkspaceDispatchCenterRoute: typeof OrganisationOrgSlugWorkspaceDispatchCenterRoute
  OrganisationOrgSlugWorkspaceDocumentsRoute: typeof OrganisationOrgSlugWorkspaceDocumentsRoute
  OrganisationOrgSlugWorkspaceFleetOperationsRoute: typeof OrganisationOrgSlugWorkspaceFleetOperationsRoute
  OrganisationOrgSlugWorkspaceFuelIntelligenceRoute: typeof OrganisationOrgSlugWorkspaceFuelIntelligenceRoute
  OrganisationOrgSlugWorkspaceKpiScorecardRoute: typeof OrganisationOrgSlugWorkspaceKpiScorecardRoute
  OrganisationOrgSlugWorkspaceMaintenanceRoute: typeof OrganisationOrgSlugWorkspaceMaintenanceRoute
  OrganisationOrgSlugWorkspaceOrganisationRoute: typeof OrganisationOrgSlugWorkspaceOrganisationRoute
  OrganisationOrgSlugWorkspaceReportsRoute: typeof OrganisationOrgSlugWorkspaceReportsRoute
  OrganisationOrgSlugWorkspaceRouteIntelligenceRoute: typeof OrganisationOrgSlugWorkspaceRouteIntelligenceRoute
  OrganisationOrgSlugWorkspaceSafetyIncidentsRoute: typeof OrganisationOrgSlugWorkspaceSafetyIncidentsRoute
  OrganisationOrgSlugWorkspaceSystemSettingsRoute: typeof OrganisationOrgSlugWorkspaceSystemSettingsRoute
  OrganisationOrgSlugWorkspaceTripsDeliveriesRoute: typeof OrganisationOrgSlugWorkspaceTripsDeliveriesRoute
  OrganisationOrgSlugWorkspaceUsersAccessRoute: typeof OrganisationOrgSlugWorkspaceUsersAccessRoute
  OrganisationOrgSlugWorkspaceIndexRoute: typeof OrganisationOrgSlugWorkspaceIndexRoute
}

const OrganisationOrgSlugWorkspaceRouteChildren: OrganisationOrgSlugWorkspaceRouteChildren =
  {
    OrganisationOrgSlugWorkspaceActionCenterRoute:
      OrganisationOrgSlugWorkspaceActionCenterRoute,
    OrganisationOrgSlugWorkspaceAuditTrailRoute:
      OrganisationOrgSlugWorkspaceAuditTrailRoute,
    OrganisationOrgSlugWorkspaceDispatchCenterRoute:
      OrganisationOrgSlugWorkspaceDispatchCenterRoute,
    OrganisationOrgSlugWorkspaceDocumentsRoute:
      OrganisationOrgSlugWorkspaceDocumentsRoute,
    OrganisationOrgSlugWorkspaceFleetOperationsRoute:
      OrganisationOrgSlugWorkspaceFleetOperationsRoute,
    OrganisationOrgSlugWorkspaceFuelIntelligenceRoute:
      OrganisationOrgSlugWorkspaceFuelIntelligenceRoute,
    OrganisationOrgSlugWorkspaceKpiScorecardRoute:
      OrganisationOrgSlugWorkspaceKpiScorecardRoute,
    OrganisationOrgSlugWorkspaceMaintenanceRoute:
      OrganisationOrgSlugWorkspaceMaintenanceRoute,
    OrganisationOrgSlugWorkspaceOrganisationRoute:
      OrganisationOrgSlugWorkspaceOrganisationRoute,
    OrganisationOrgSlugWorkspaceReportsRoute:
      OrganisationOrgSlugWorkspaceReportsRoute,
    OrganisationOrgSlugWorkspaceRouteIntelligenceRoute:
      OrganisationOrgSlugWorkspaceRouteIntelligenceRoute,
    OrganisationOrgSlugWorkspaceSafetyIncidentsRoute:
      OrganisationOrgSlugWorkspaceSafetyIncidentsRoute,
    OrganisationOrgSlugWorkspaceSystemSettingsRoute:
      OrganisationOrgSlugWorkspaceSystemSettingsRoute,
    OrganisationOrgSlugWorkspaceTripsDeliveriesRoute:
      OrganisationOrgSlugWorkspaceTripsDeliveriesRoute,
    OrganisationOrgSlugWorkspaceUsersAccessRoute:
      OrganisationOrgSlugWorkspaceUsersAccessRoute,
    OrganisationOrgSlugWorkspaceIndexRoute:
      OrganisationOrgSlugWorkspaceIndexRoute,
  }

const OrganisationOrgSlugWorkspaceRouteWithChildren =
  OrganisationOrgSlugWorkspaceRoute._addFileChildren(
    OrganisationOrgSlugWorkspaceRouteChildren,
  )

interface OrganisationOrgSlugRouteChildren {
  OrganisationOrgSlugWorkspaceRoute: typeof OrganisationOrgSlugWorkspaceRouteWithChildren
  OrganisationOrgSlugLoginRoute: typeof OrganisationOrgSlugLoginRoute
}

const OrganisationOrgSlugRouteChildren: OrganisationOrgSlugRouteChildren = {
  OrganisationOrgSlugWorkspaceRoute:
    OrganisationOrgSlugWorkspaceRouteWithChildren,
  OrganisationOrgSlugLoginRoute: OrganisationOrgSlugLoginRoute,
}

const OrganisationOrgSlugRouteWithChildren =
  OrganisationOrgSlugRoute._addFileChildren(OrganisationOrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OrganisationOrgSlugRoute: OrganisationOrgSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
